trigger:
- main

pool:
  name: my-agent

steps:

- script: |
    docker --version
    docker build -t myapp:latest ./frontend
  displayName: 'Build Docker Image'

- script: |
    docker images
  displayName: 'Check Docker Image'
